import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "@stream-io/video-react-sdk/dist/css/styles.css";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StreamIOClientProvider from "@/providers/StreamIOClientProviders";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Roboto } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={roboto.variable}>
        <body className={`antialiased flex`}>
          <StreamIOClientProvider>
            <AppRouterCacheProvider options={{enableCssLayer: true}}>
              <ThemeProvider theme={theme}>
                <Navbar />
                <main className="w-[87%]">{children}</main>
              </ThemeProvider>
            </AppRouterCacheProvider>
          </StreamIOClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
